### ISSUE TITLE
Can't install (from pip3) in Python 3.9

### ISSUE THREAD

**Issue by BernardGreenberg** [tobywf/pasteboard#7]
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'

Looking forward, thanks.

**Comment by tobywf** [comment]
Sorry about this. Python 3.9 isn't yet supported, as detailed in the classifiers on PyPI (even though pinning does not prevent newer releases). You can work around this until I can release a new version with:
```
pip install pasteboard --no-use-pep517
```

**Comment by BernardGreenberg** [comment]
That succeeded, thanks.
________________________________

**Comment by tobywf** [comment]
I've uploaded a new version to PyPI, should fix the problem in the future. Let me know if it doesn't!

**Comment by spyoungtech** [comment]
Hey there, I'm using Python 3.8 and am having this issue. When doing `pip install pasteboard` I get a similar traceback that results in the error:

```
  ----------------------------------------
  ERROR: Failed building wheel for pasteboard
Failed to build pasteboard
ERROR: Could not build wheels for pasteboard which use PEP 517 and cannot be installed directly
```

I tried `pip install pasteboard --no-use-pep517` but got the following error:


```
 $ pip install pasteboard --no-use-pep517

Collecting pasteboard
  Using cached pasteboard-0.3.2.tar.gz (11 kB)
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of poetry.core.masonry.api in pyproject.toml
```

Any ideas?

**Comment by spyoungtech** [comment]
FWIW, this works: `pip install "pasteboard<0.3.2" --no-use-pep517`

I would like to include this package as a dependency in one of my own projects, but adding it as a dependency in my `setup.py` causes pip install to break for this reason 😞

So, it would be nice to have install work without the `--no-use-pep517` flag, since I don't think it's possible to designate this as part of my own `setup.py`

**Comment by tobywf** [comment]
I think there's two problems. One is I have to publish wheels for each Python version so it doesn't build from source. Two is that it seems to me `poetry` is emitting a `setup.py`, I'm not sure why, maybe because of the compilation step. This seems to then have an implicit dependency on `setuptools`, which isn't pulled into the build process if it isn't declared, even if it's present in the virtualenv. The relevant log  is above "ERROR: Failed building wheel for pasteboard":

```
  Building wheel for pasteboard (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: env/bin/python3 env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/lw/j2ckppbd37z43y8j
8ckmd46h0000gn/T/tmphd_p2yxk
       cwd: <temp>/pip-install-xp3a0f3w/pasteboard
  Complete output (25 lines):
  A setup.py file already exists. Using it.
  Traceback (most recent call last):
    File "fpip-install-xp3a0f3w/pasteboard/setup.py", line 2, in <module>
      from setuptools import setup
  ModuleNotFoundError: No module named 'setuptools'
  Traceback (most recent call last):
    File "env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "<temp>/pip-build-env-k13d1rd5/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    [...]
    File "<temp>/pip-build-env-k13d1rd5/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 149, in _run_build_command
      subprocess.check_call(
    File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['env/bin/python3', '<temp>/pip-install-xp3a0f3w/pasteboard/setup.py', 'build', '
-b', '<temp>/pip-install-xp3a0f3w/pasteboard/build']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pasteboard
```

That should be an easy fix, building multiple wheels might take a bit...

**Comment by tobywf** [comment]
The fix will work and I'll push it shortly. I wanted to fully understand the fix before releasing it; turns out this is messy. Unbeknownst to me, poetry generates a `setup.py` to maintain compatibility for old pip versions that don't support PEP 517. I maybe should've guessed that based on how `build.py` works.

However, this breaks on newer pip versions that support PEP 517. First, pip calls poetry (more specifically, poetry-core), because a `pyproject.toml` exists. Then, poetry-core sees a `setup.py` exists already, [and uses that](https://github.com/python-poetry/poetry-core/blob/1.0.0/poetry/core/masonry/builders/sdist.py#L208-L215). Unfortunately, because pip thinks it's using PEP 517, [setuptools isn't automatically included](https://pip.pypa.io/en/stable/reference/pip/):

> Projects using PEP 517 *must* explicitly use setuptools - pip does not do the above injection process in this case.

It's unfortunate the Python package ecosystem is in such a state. I can hardly blame poetry for the workaround. I may drop support for older pip versions soon and move to a pure PEP 517-based install, but for now, this'll work.

**Comment by tobywf** [comment]
Release [v0.3.3](https://github.com/tobywf/pasteboard/releases/tag/v0.3.3) should fix building from source, and also includes pre-build wheels for Python 3.6, 3.7, 3.8, and 3.9 (should work on macOS 10.15 Catalina and up). Let me know how it goes!

**Comment by spyoungtech** [comment]
@tobywf works perfectly. Thank you for this!

**Comment by kylephan5** [comment]
Hey, what is it that I need to do? I'm getting the error that you got: "Failed building wheel for pasteboard"

**Comment by spyoungtech** [comment]
@kylephan5 the original issue discussed here was fixed. You are probably running into a new problem and you may want to file a new issue accordingly.

A couple quick thoughts:

- Are you perhaps using a version of Python greater than 3.9 or less than 3.6? -- if so, try a version of Python between 3.6 and 3.9 and see if the problem goes away.
- Or maybe running on a Mac using a M1 or M2 processor?

These would be good to mention if you decide to open a new issue :-)
